apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quay-login
secrets:
  - name: quay-secret